vars:
  AWESOME: cat
  NAUDINGAS: lietuvių kalba

vars-bash:
  TESTING: lietuvių kalba

on_enter:
  - "echo 'hi'"
  - "echo 'lol'"

on_exit:
  - "echo 'bye!'"

aliases:
   cowsay: "cowsay -f /usr/share/cowsay/cows/default.cow"

aliases-fish:
   hi: "echo 'hi'"

aliases-bash:
   sigh: "echo 'hi'"

hooks:
  "git": "echo labas"
